[package]
name = "rusty-fractals"
version = "0.1.1"
edition = "2021"
authors = ["Mike Croall"]

[dependencies]
pixels = "0.13.0"
winit = "0.28.6"
winit_input_helper = "0.14.1"
log = "0.4.19"
env_logger = "0.10.0"
error-iter = "0.4.1"
num = "0.4.1"
colors-transform = "0.2.4"
rayon = "1.7"
